---
title: "cluster Artist"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(ggplot2)
library(gridExtra)
library(lme4)
library(lmerTest)
library(dplyr)
library(tidyr)
library(knitr)
library(plotly)
library(changepoint)
```

```{r, echo = FALSE}
# Load data
artist <- read.csv ("H:\\NIDA\\Artist\\analysisArtistNoEngage.csv")
artistT <- read.csv ("H:\\NIDA\\Artist\\artistTimes.csv")
validArtist <- filter(artist, valid == 1)
engageArtist <- filter (artist, !((valid == 0) & (incorrect == 0)))
```

```{r}
completePair <- validArtist[validArtist$Experiment == 1, -4]
for (i in 1:(nrow(validArtist)/2)){
  lane <- validArtist$SD.Lane.Deviation[(2*i-1)] - validArtist$SD.Lane.Deviation[(2*i)]
  speed <- validArtist$Avg.Speed[(2*i-1)] - validArtist$Avg.Speed[(2*i)]
  sdspeed <- validArtist$SD.Speed[(2*i-1)] - validArtist$SD.Speed[(2*i)]
  completePair[i,"diffSDLane"] <- lane
  completePair[i,"diffAvgSpeed"] <- speed
  completePair[i,"diffSDSpeed"] <- sdspeed
}
```

```{r}
completePairEngage <- engageArtist[engageArtist$Experiment == 1, -4]
for (i in 1:(nrow(validArtist)/2)){
  lane <- engageArtist$SD.Lane.Deviation[(2*i-1)] - engageArtist$SD.Lane.Deviation[(2*i)]
  speed <- engageArtist$Avg.Speed[(2*i-1)] - engageArtist$Avg.Speed[(2*i)]
  sdspeed <- engageArtist$SD.Speed[(2*i-1)] - engageArtist$SD.Speed[(2*i)]
  completePairEngage[i,"diffSDLane"] <- lane
  completePairEngage[i,"diffAvgSpeed"] <- speed
  completePairEngage[i,"diffSDSpeed"] <- sdspeed
}
```

# Valid Artist:
# 2 Clusters: 
# Cluster 1
```{r}
cluster1 <- filter (validArtist, ID %in% c(7, 18, 29, 34, 120, 123))

fit <- lmer(SD.Lane.Deviation ~ factor(Experiment) +  BAC + THC + Avg.Speed + (1| ID) + factor (pageNum), data = cluster1)
summary(fit)
# BAC and THC not significant
# Avg.Speed significant

fit <- lmer(Avg.Speed ~ factor(Experiment) +  BAC + THC + (1| ID) + factor (pageNum), data = cluster1)
summary(fit)
# BAC and THC not significant

fit <- lmer(SD.Speed ~ factor(Experiment) +  BAC + THC + (1| ID) + factor (pageNum), data = cluster1)
summary(fit)
anova(fit)
# BAC and THC not significant
```

## Paired
```{r}
cluster1pair <- filter (completePair, ID %in% c(7, 18, 29, 34, 120, 123))

fit <- lmer(diffSDLane ~ BAC + THC + Avg.Speed +(1| ID) + factor (pageNum), data = cluster1pair)
summary(fit)
anova(fit)
# BAC and THC not significant
# Avg.Speed not significant

fit <- lmer(diffAvgSpeed ~ BAC + THC + (1| ID) + factor (pageNum), data = cluster1pair)
summary(fit)
anova(fit)
# BAC and THC not significant

fit <- lmer(diffSDSpeed ~ BAC + THC + (1| ID) + factor (pageNum), data = cluster1pair)
summary(fit)
anova(fit)
# BAC and THC not significant
```

# Cluster 2
```{r}
cluster2 <- filter (validArtist, !(ID %in% c(7, 18, 29, 34, 120, 123)))

fit <- lmer(SD.Lane.Deviation ~ factor(Experiment) +  BAC + THC + Avg.Speed + (1| ID) + factor (pageNum), data = cluster2)
summary(fit)
# BAC and THC not significant

fit <- lmer(Avg.Speed ~ factor(Experiment) +  BAC + THC + (1| ID) + factor (pageNum), data = cluster2)
summary(fit)
anova(fit)
# BAC and THC not significant
# pageNum is significant

fit <- lmer(SD.Speed ~ factor(Experiment) +  BAC + THC + (1| ID) + factor (pageNum), data = cluster2)
summary(fit)
anova(fit)
# BAC and THC not significant
```

## Paired
```{r}
cluster2pair <- filter (completePair, !(ID %in% c(7, 18, 29, 34, 120, 123)))

fit <- lmer(diffSDLane ~ BAC + THC + Avg.Speed +(1| ID) + factor (pageNum), data = cluster2pair)
summary(fit)
anova(fit)
# BAC and THC not significant
# Avg.Speed not significant

fit <- lmer(diffAvgSpeed ~ BAC + THC + (1| ID) + factor (pageNum), data = cluster1pair)
summary(fit)
anova(fit)
# BAC and THC not significant

fit <- lmer(diffSDSpeed ~ BAC + THC + (1| ID) + factor (pageNum), data = cluster1pair)
summary(fit)
anova(fit)
# BAC and THC not significant
```

# Engaged Artist
# 2 Clusters:
# Cluster 1
```{r}
cluster1 <- filter (engageArtist, ID %in% c(7, 18, 29, 34, 120, 123))

fit <- lmer(SD.Lane.Deviation ~ factor(Experiment) +  BAC + THC + Avg.Speed + (1| ID) + factor (pageNum), data = cluster1)
summary(fit)
# THC and BAC not significant

fit <- lmer(Avg.Speed ~ factor(Experiment) +  BAC + THC + (1| ID) + factor (pageNum), data = cluster1)
summary(fit)
# THC and BAC not significant.  

fit <- lmer(SD.Speed ~ factor(Experiment) +  BAC + THC + (1| ID) + factor (pageNum), data = cluster1)
summary(fit)
# THC and BAC not significant
```

# Paired
```{r}
cluster1pair <- filter (completePairEngage, ID %in% c(7, 18, 29, 34, 120, 123))

fit <- lmer(diffSDLane ~ BAC + THC + Avg.Speed +(1| ID) + factor (pageNum), data = cluster1pair)
summary(fit)
anova(fit)
# THC              -0.03229    0.01458 59.00000  -2.215  0.03065 *
# Avg.Speed marginally significan
plot(cluster1pair$THC, cluster1pair$diffSDLane)

fit <- lmer(diffAvgSpeed ~ BAC + THC + (1| ID) + factor (pageNum), data = cluster1pair)
summary(fit)
anova(fit)
# BAC and THC not significant

fit <- lmer(diffSDSpeed ~ BAC + THC + (1| ID) + factor (pageNum), data = cluster1pair)
summary(fit)
anova(fit)
#  BAC and THC not significant
```

# Cluster 2
```{r}
cluster2 <- filter (engageArtist, !(ID %in% c(7, 18, 29, 34, 120, 123)))

fit <- lmer(SD.Lane.Deviation ~ factor(Experiment) +  BAC + THC + Avg.Speed + (1| ID) + factor (pageNum), data = cluster2)
summary(fit)
# BAC                   2.826547   1.594982 310.080481   1.772 0.077352 .  
#THC                  -0.020093   0.010114 264.475618  -1.987 0.047986 *  
# Experiment significant

fit <- lmer(Avg.Speed ~ factor(Experiment) +  BAC + THC + (1| ID) + factor (pageNum), data = cluster2)
summary(fit)
anova(fit)
# BAC and THC not significant
# pageNum is significant

fit <- lmer(SD.Speed ~ factor(Experiment) +  BAC + THC + (1| ID) + factor (pageNum), data = cluster2)
summary(fit)
anova(fit)
# BAC and THC not significant
```

## Paired
```{r}
cluster2pair <- filter (completePairEngage, !(ID %in% c(7, 18, 29, 34, 120, 123)))

fit <- lmer(diffSDLane ~ BAC + THC + Avg.Speed +(1| ID) + factor (pageNum), data = cluster2pair)
summary(fit)
anova(fit)
# BAC and THC not significant
# Avg.Speed not significant

fit <- lmer(diffAvgSpeed ~ BAC + THC + (1| ID) + factor (pageNum), data = cluster1pair)
summary(fit)
anova(fit)
# BAC and THC not significant

fit <- lmer(diffSDSpeed ~ BAC + THC + (1| ID) + factor (pageNum), data = cluster1pair)
summary(fit)
anova(fit)
# BAC and THC not significant
```
