    
---
title: "Side Mirror"
author: "Stella Lee"
date: "July 16, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(ggplot2)
library(gridExtra)
library(lme4)
library(lmerTest)
library(dplyr)
library(tidyr)
library(knitr)
library(plotly)
library(changepoint)
```

```{r, echo = FALSE}
# Load data
mirror <- read.csv ("H:\\NIDA\\analysisMirror.csv")
# this already changed 299 frames to valid = 0 
mirror <- dplyr::filter (mirror, total <= 300)
```

```{r}
table(mirror$valid, mirror$DosingLevel)
prop.table(table(mirror$valid))
prop.table(table(mirror$DosingLevel, mirror$valid), 1)
## Fit a mixed effects logistic regression model
## Outcome is whether subject failed to complete a task
fit <- glm((valid == 0) ~ BAC + THC, data = mirror, family = "binomial")
summary(fit)
# both (BAC and THC) not significant
fit <- glmer((valid == 0) ~ BAC + THC + (1 | ID) + factor(Visit), data = mirror, family = "binomial")
summary(fit)
anova(fit)
# THC = 0.04836 * BAC = 0.09770 .
```

# Without participant 123
```{r}
normalMirror <- filter(mirror, ID != 123) # XP 100% incomplete, Visit 1
prop.table(table(normalMirror$valid))
prop.table(table(normalMirror$Visit, normalMirror$valid), 1)
length(table(normalMirror$ID))

fit <- glm((valid == 0) ~ DosingLevel, data = normalMirror, family = "binomial")
summary (fit)
fit <- glm((valid == 0) ~ BAC + THC, data = normalMirror, family = "binomial")
summary(fit)

fit <- glmer((valid == 0) ~ BAC + THC + (1 | ID) + (Visit > 1), data = normalMirror, family = "binomial")
fit <- glmer(valid ~ BAC + THC + (1 | ID) + factor(eventNum), data = normalMirror, family = "binomial")
summary(fit)
anova(fit)
summary(fit)
kable(round(summary(fit)$coefficients, 4))
coefs <- summary(fit)$coefficients[,1]
ses <- summary(fit)$coefficients[,2]
kable(round(exp(data.frame(OR = coefs, LCL = coefs - 1.96*ses, UCL = coefs + 1.96*ses)), 4))
```

# Complete tasks
```{r}
complete <- filter(mirror, valid == 1) 
complete$time <- complete$total / 60
# total time
fit <- lmer (total ~ BAC + THC + (1 | ID) + (Visit > 1) + factor(LogStreams.5), data = complete)
summary(fit)
```

Lane Deviation
```{r}
fit <- lmer(SD.Lane.Deviation ~ factor(Experiment) +  BAC + THC + time + Avg.Speed  +  (1| ID) + factor (Visit) + factor(LogStreams.5), data = complete)
# BAC
summary (fit)
anova(fit)
coefs <- summary(fit)$coefficients[,1]
ses <- summary(fit)$coefficients[,2]
kable(round(exp(data.frame(OR = coefs, LCL = coefs - 1.96*ses, UCL = coefs + 1.96*ses)), 4))
```

Avg Speed
```{r}
fit <- lmer(Avg.Speed ~ factor(Experiment)  + BAC + THC + (1| ID) + factor (Visit) + factor(LogStreams.5), data = complete)
fit <- lmer(Avg.Speed ~ factor(Experiment)  + BAC + THC + time + (1| ID) + factor (Visit) + factor(LogStreams.5), data = complete)
# THC, BAC, THC:BAC marginally significant
#summary (fit)
anova(fit)
```

SD Speed
```{r}
fit <- lmer(SD.Speed ~ factor(Experiment) +  BAC + THC + BAC:THC + (1| ID) + time + factor (Visit) + factor(LogStreams.5), data = complete)
# BAC
#summary (fit)
anova(fit)
```
