    
---
title: "Side Mirror"
author: "Stella Lee"
date: "July 16, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(ggplot2)
library(gridExtra)
library(lme4)
library(lmerTest)
library(dplyr)
library(tidyr)
library(knitr)
library(plotly)
library(changepoint)
```

```{r, echo = FALSE}
# Load data
mirror <- read.csv ("H:\\NIDA\\analysisMirror.csv")
# this already changed 299 frames to valid = 0 
mirror <- dplyr::filter (mirror, total <= 300)
```

```{r}
table(mirror$valid, mirror$DosingLevel)
prop.table(table(mirror$valid))
prop.table(table(mirror$DosingLevel, mirror$valid), 1)
## Fit a mixed effects logistic regression model
## Outcome is whether subject failed to complete a task
fit <- glm((valid == 0) ~ BAC + THC, data = mirror, family = "binomial")
summary(fit)
# both (BAC and THC) not significant
fit <- glmer((valid == 0) ~ BAC + THC + (1 | ID) + factor(Visit), data = mirror, family = "binomial")
summary(fit)
anova(fit)
# THC = 0.04836 * BAC = 0.09770 .
```

# Without participant 123
```{r}
normalMirror <- filter(mirror, ID != 123) # XP 100% incomplete, Visit 1
prop.table(table(normalMirror$valid))
prop.table(table((normalMirror$Visit>1), normalMirror$valid), 1)
length(table(normalMirror$ID))

fit <- glm((valid == 0) ~ DosingLevel, data = normalMirror, family = "binomial")
summary (fit)
fit <- glm((valid == 0) ~ BAC + THC, data = normalMirror, family = "binomial")
summary(fit)

fit <- glmer((valid == 0) ~ BAC + THC + BAC:THC + (1 | ID) + (Visit > 1), data = normalMirror, family = "binomial")
fit <- glmer(valid ~ BAC + THC + (1 | ID) + factor(eventNum), data = normalMirror, family = "binomial")
summary(fit)
anova(fit)
summary(fit)
kable(round(summary(fit)$coefficients, 4))
coefs <- summary(fit)$coefficients[,1]
ses <- summary(fit)$coefficients[,2]
kable(round(exp(data.frame(OR = coefs, LCL = coefs - 1.96*ses, UCL = coefs + 1.96*ses)), 4))
```

# Complete tasks
```{r}
complete <- filter(mirror, valid == 1) 
complete$time <- complete$total / 60
# total time
fit <- lmer (total ~ BAC + THC + (1 | ID) + (Visit > 1) + factor(LogStreams.5), data = complete)
summary(fit)
```

Lane Deviation
```{r}
fit <- lmer(SD.Lane.Deviation ~ factor(Experiment) +  BAC + THC + Avg.Speed  +  (1| ID) + factor (Visit) + factor(LogStreams.5), data = complete)
# BAC
summary (fit)
anova(fit)
coefs <- summary(fit)$coefficients[,1]
ses <- summary(fit)$coefficients[,2]
kable(round(exp(data.frame(OR = coefs, LCL = coefs - 1.96*ses, UCL = coefs + 1.96*ses)), 4))
```

Avg Speed
```{r}
fit <- lmer(Avg.Speed ~ factor(Experiment)  + BAC + THC + (1| ID) + factor (Visit) + factor(LogStreams.5), data = complete)
fit <- lmer(Avg.Speed ~ factor(Experiment)  + BAC + THC + time + (1| ID) + factor (Visit) + factor(LogStreams.5), data = complete)
# THC, BAC, 
summary (fit)
anova(fit)
AIC(fit) # 19848.97

fit <- lmer(Avg.Speed ~ factor(Experiment)  + BAC  + THC + BAC:THC +  (1| ID) + factor (Visit) + factor(LogStreams.5), data = complete)
anova(fit)
summary (fit) #THC:BAC significant
AIC (fit) # 19840.62 
```

SD Speed
```{r}
fit <- lmer(SD.Speed ~ factor(Experiment) +  BAC + THC + BAC:THC + (1| ID) + time + factor (Visit) + factor(LogStreams.5), data = complete)
# BAC
summary (fit)
anova(fit)
```

# Paired Difference

```{r}
completePair <- complete[complete$Experiment == 1, c(1:4, 6, 9, 13:16)]
for (i in 1:(nrow(complete)/2)){
  lane <- complete$SD.Lane.Deviation[(2*i-1)] - complete$SD.Lane.Deviation[(2*i)]
  speed <- complete$Avg.Speed[(2*i-1)] - complete$Avg.Speed[(2*i)]
  sdspeed <- complete$SD.Speed[(2*i-1)] - complete$SD.Speed[(2*i)]
  completePair[i,"diffSDLane"] <- lane
  completePair[i,"diffAvgSpeed"] <- speed
  completePair[i,"diffSDSpeed"] <- sdspeed
}
```

# Plots

```{r}
completePair$road <- ifelse (completePair$LogStreams.5 <= 14, "urban", ifelse(completePair$LogStreams.5 <= 22, "interstate", "rural"))
# Difference by road segments 
ggplot(completePair, aes(x = road, y = diffSDLane)) + geom_boxplot(outlier.shape = NA) + geom_jitter(width = .15) + geom_abline(intercept = 0, slope = 0, lty = "dashed") + labs(y = "Paired within subject difference")
ggplot(completePair, aes(x = road, y = diffAvgSpeed)) + geom_boxplot(outlier.shape = NA) + geom_jitter(width = .15) + geom_abline(intercept = 0, slope = 0, lty = "dashed") + labs(y = "Paired within subject difference")
## Lane deviation is different in interstate

# Difference in SD Lane Deviation
ggplot(completePair, aes(x = (BAC > 0), y = diffSDLane)) + geom_boxplot(outlier.shape = NA) + geom_jitter(width = .15) + geom_abline(intercept = 0, slope = 0, lty = "dashed") + labs(y = "Paired within subject difference")

# Difference in Avg speed 
ggplot(completePair, aes(x = THC, y = diffAvgSpeed, color = road)) + geom_point()
ggplot(completePair, aes(x = BAC, y = diffAvgSpeed, color = road)) + geom_point()
```

# Models
```{r}
fit <- lmer(diffSDLane ~ BAC + THC + diffAvgSpeed  +  (1| ID) + factor (Visit) + factor(LogStreams.5), data = completePair)
summary(fit)
anova(fit)
# THC and BAC not significant
# difference in average speed and road segment is significant
fit <- lmer(diffAvgSpeed ~ BAC + THC + (1| ID) + factor (Visit) + factor(LogStreams.5), data = completePair)
summary(fit)
anova(fit)
# THC is significant (p = 0.008415) with coefficient -1.326e-02
# BAC is not significant
fit <- lmer(diffSDSpeed ~ BAC: THC + (1| ID) + factor (Visit) + factor(LogStreams.5), data = completePair)
summary(fit)
anova(fit)
# THC and BAC not significant
# difference in average speed and road segment is also not significant
AIC(fit)
```
# Clustering results
```{r}
THCrange <- NULL
for (i in unique(mirror$ID)){
  temp <- filter(mirror, ID == i)
  THCrange <- rbind.data.frame(THCrange, c(i, max(temp$THC), min(temp$THC), (max(temp$THC) - min(temp$THC))))
}
colnames(THCrange) <- c("ID", "max", "min", "range")
rownames(THCrange) <- THCrange$ID
k2 <- kmeans(THCrange[, 4], centers = 2, nstart = 25)
fviz_cluster(k2, data = THCrange)
# Cluster 1: Participant 7, 18, 29, 34, 120, 123

k3 <- kmeans(THCrange[, 4], centers = 3, nstart = 25)
fviz_cluster(k3, data = THCrange)
# Cluster 1: Participant 7, 18
# cluster 2: Participant 29, 31, 34, 120, 123
```

# Cluster 1
```{r}
cluster1 <- filter (complete, ID %in% c(7, 18, 29, 34, 120, 123))

fit <- lmer(Avg.Speed ~ factor(Experiment) +  BAC + THC + Avg.Speed  +  (1| ID) + factor (Visit) + factor(LogStreams.5), data = cluster1)
summary(fit)
# BAC p = 0.005 coef = 18.827
# THC p = 0.021 coef = -0.059
# Experiment not significant

cluster1pair <- filter (completePair, ID %in% c(7, 18, 29, 34, 120, 123))
fit <- lmer(diffSDLane ~ BAC + THC + Avg.Speed +  (1| ID) + factor(LogStreams.5) , data = cluster1pair)
summary(fit)
anova(fit)
# not significant

fit <- lmer(diffAvgSpeed ~ BAC + THC + (1| ID)+ factor(LogStreams.5), data = cluster1pair)
summary(fit)
anova(fit)
# THC p = 0.002 coef = -0.017
```

# Cluster 2
```{r}
cluster2 <- filter (complete, !(ID %in% c(7, 18, 29, 34, 120, 123)))
cluster2pair <- filter (completePair, !(ID %in% c(7, 18, 29, 34, 120, 123)))
fit <- lmer(Avg.Speed ~ factor(Experiment) +  BAC + THC + Avg.Speed  +  (1| ID) + factor (Visit) + factor(LogStreams.5), data = cluster2)
summary(fit)
# BAC p = 0.004278 coef = 16.77858
# THC p = 4.38e-05 coef = -0.18520
# Experiment not significant

cluster2pair <- filter (completePair, !(ID %in% c(7, 18, 29, 34, 120, 123)))
fit <- lmer(diffSDLane ~ BAC + THC + Avg.Speed +  (1| ID) + factor(LogStreams.5) , data = cluster2pair)
summary(fit)
anova(fit)
# not significant

fit <- lmer(diffAvgSpeed ~ BAC + THC + (1| ID)+ factor(LogStreams.5), data = cluster2pair)
summary(fit)
anova(fit)
# not significant
```
